### PR TITLE
[WIP] deployment at SDSC

### PR DESCRIPTION
**Pull request by zonca**
Following https://github.com/jupyterhub/batchspawner/issues/12 I prepared an example based on our configuration at SDSC.

I chose a folder name that is a summary of the configuration details.

Documentation is part in the `README.md` and part in the docstrings.

@mbmilligan, @minrk  some suggestions? either on the setup itself or on documentation?

For convenience, here direct link to the [rendered README](https://github.com/zonca/jupyterhub-deploy-hpc/blob/4ebf6ba2637637eb0929c267e3557a4df3e808bc/batchspawner-xsedeoauth-sshtunnel-sdsccomet/README.md)

### CODE REVIEW

**Comment by mbmilligan** [comment]
Nice, thanks for contributing this! Now I'm both inspired to finish documenting my setup and have a reasonable template for it too.

In terms of suggestions, I guess things I would like to see added would be:
- mention explicitly what software needs to be installed on the Hub and compute hosts (looks like you're using conda packages, but also system packages like `supervisord`) -- this probably merits its own heading in the README
- note what, if any, deployment automation or central configuration management you are using -- a point that keeps coming up when I talk to devops types about this is the question of whether Jupyterhub can play nicely with such systems (YES!)

**Comment by zonca** [comment]
thanks @mbmilligan !

added Requirements to the README.

No deployment automation for this, I feel like the setup is quite simple on the system side. Also I don't plan to deploy many of this HPC-connected instances. So I think an ansible playbook would be too much.

Instead for teaching workshops or classes, where you want to deploy many times, Ansible works great, see: https://github.com/jupyterhub/jupyterhub-deploy-teaching

**Comment by mbmilligan** [comment]
I like it, thanks!

**Comment by willingc** [comment]
@zonca and @mbmilligan 🍰 🍪 Thanks!

**Pull request merged**
